services:
  db:
    restart: unless-stopped
    image: postgres:15.4-alpine3.18
    volumes:
      - 'dbstore:/var/lib/postgresql/data'
    ports:
      - '5437:5432'
    environment:
      - POSTGRES_USER=repo
      - POSTGRES_PASSWORD=repo
      - POSTGRES_DB=repo_dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U repo -d repo_dev']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  mail:
    restart: unless-stopped
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
  minio:
    restart: unless-stopped
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /data/repo && /usr/bin/docker-entrypoint.sh server --console-address ":9001" /data'
    # network_mode: 'host'
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=repostorage
      - MINIO_ROOT_PASSWORD=repostorage
      - MINIO_NOTIFY_WEBHOOK_ENABLE_API_FILESYSTEM_S3=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_API_FILESYSTEM_S3=http://localhost:8080/minio/webhooks/events
      - MINIO_ACCESS_KEY=repostorage
      - MINIO_SECRET_KEY=repostorage
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  dbstore:
  meili_data:
  minio-data:
  redis-data:
