name: Deploy to AWS

on:
  push:
    
env:
  CI: true
  AWS_ACCOUND_ID: '412395869197'
  NODE_OPTIONS: '--max-old-space-size=4096'
  STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' ||  github.ref == 'refs/heads/test' && 'test' || 'uat'  }}

jobs:
  deployment:
    name: Deploy App
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' ||  github.ref == 'refs/heads/test' && 'test' || 'uat'  }}
      url: ${{ github.ref == 'refs/heads/main' && 'https://cms.num.co.za' || github.ref == 'refs/heads/test' && 'https://num.technanimals.com' || 'https://num.uat-digitech.co.za'}}
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          node-version: '18.x'

      - name: Restore build cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn
      - name: Build
        run: yarn run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUND_ID }}:role/github-action-technanimals-role
          aws-region: eu-west-1

      - name: Deploy
        run: |
          yarn sst deploy --stage=${{ env.STAGE }}
